### ISSUE TITLE
x11Grab is an unknown input

### ISSUE THREAD

**Issue by Wolfleader101** [blueimp/record-screen#3]
```
Unknown input format: 'x11grab'

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
```
I don't know why i am getting this error and i cant find the solution too it.

**Comment by blueimp** [comment]
How are you using this library?
https://github.com/blueimp/record-screen/blob/master/README.md#usage

`x11grab` is the default input format, but is only available on Linux with the X11 window system.

Since `ffmpeg` returns that this input format is unknown, you are likely not running this on Linux, or ffmpeg has not been compiled with support for that format.

If you’re on another system, you likely want to use the `mjpeg` input format instead:

https://github.com/blueimp/record-screen/blob/master/README.md#mjpeg

**Comment by Wolfleader101** [comment]
when i used mjpeg i got
```[tcp @ 0000020c0aa0c940] Connection to tcp://localhost:9000 failed: Error number -138 occurred
http://localhost:9000/: Unknown error

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: true,
  code: null,
  signal: 'SIGINT',
  cmd: 'ffmpeg -y -r 15 -f mjpeg -i http://localhost:9000/ -pix_fmt yuv420p /tmp/test.mp4'
}```

**Comment by blueimp** [comment]
The `killed: true` signifies that the process was killed by a supervising process.
Needs further context on how you're running this to get to the root cause.

By the way if you're using the `mjpeg` input, you also need an MJPEG server running that ffmpeg can connect to, e.g. https://github.com/blueimp/mjpeg-server

I should point out that this library is aimed at recording remote screens, as its original use case was for recording selenium/webdriver controlled browser sessions from a Docker container.

If you want to record a MacOS or Windows desktop directly, you might wanna construct your own ffmpeg command line or use a a more generalized Node.js ffmpeg wrapper:
https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by Wolfleader101** [comment]
ok thank you :)
I was trying to use it within an Electron App, 
I will definitely use the server :)
